title: "[오늘 날짜] 회의록 "
labels: [아침 짧은 회의를 통한 할일 정리와 현 상황 파악]
body:
  - type: markdown
    attributes:
        value : |
          🌟 **Daily Scrum Report** 🌟
  - type : textarea
    id: Done
    attributes :
      label: ✅ 1. 어제 한 일 (What I did yesterday) 
      value : |
       - 🔹 
  - type : markdown
    attributes : 
      value : |
        ############### 📝 2. 오늘 할 일 (What I plan to do today) ###############
        🔹 각 사람별 오늘의 할일을 체크박스로 만든후 완료되면 췍
  - type: checkboxes
    attributes:
      label: 근희
      options:
        - label: 1번째
        - label: 2번째
  - type: checkboxes
    attributes:
      label: 용욱
      options:
        - label: 1번째
        - label: 2번째
  - type: checkboxes
    attributes:
      label: 이정
      options:
        - label: 1번째
        - label: 2번째
  - type: checkboxes
    attributes:
      label: 승찬
      options:
        - label: 1번째
        - label: 2번째
